# The Mumble server's address
address = "localhost"

# The Mumble server's port
port = 64738

# The username of the bot
username = "MusicBot"

# The prefix for the commands
command_prefix = "!"

# Whether to check the server's certificate
verify_server_certificate = false

# The starting volume of the bot
# Must be between 0-100
default_volume = 60

# Set this to your Google Cloud API key to enable searching youtube
# For information about getting an API key visit https://developers.google.com/youtube/v3/docs
youtube_api_key = ""

# Whether to use a certificate and where are the pem files
[certificate]
use_certificate = true
certificate_file_path = "./certs/cert.pem"
key_file_path = "./certs/key.pem"